# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160119_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 9, 6, 44, 32, 292907)),
        ),
    ]
