# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160509_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 9, 6, 46, 36, 583095)),
        ),
    ]
