# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160509_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 31, 10, 1, 50, 534148)),
        ),
    ]
