# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160531_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 10, 10, 40, 490850)),
        ),
    ]
