# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 05:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160603_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 5, 40, 28, 219450)),
        ),
    ]
