# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 07:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160608_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 8, 7, 45, 41, 630364)),
        ),
    ]
