# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=50)),
                ('theme_image', models.CharField(max_length=200)),
                ('slug_theme', models.SlugField(unique=True)),
            ],
        ),
    ]
